config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :artists
  resources :releases
  resources :albums
  resources :eps
  resources :singles
  resources :tracks
  resources :events
  resources :discography
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'home/index'
  resources :artists, only: %i[index show new create] # Puedes ajustar las acciones según tus necesidades
  resources :releases, only: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', :as => :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "id_value", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :release
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
# frozen_string_literal: true

# app/models/artist.rb
class Artist < ApplicationRecord
  validates :name, presence: true
  validates :profession, presence: true
  has_many :releases
  has_many :multimedia_items
  has_one_attached :profile_picture
  attr_accessor :biography
end

app/models/ep.rb
class Ep < ApplicationRecord
  belongs_to :release
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
end

app/models/multimedia_item.rb
class MultimediaItem < ApplicationRecord
  belongs_to :user
end

app/models/release.rb
# app/models/release.rb
class Release < ApplicationRecord
  # Asumiendo que tienes un campo adicional en tu modelo Release llamado 'description'
  validates :title, presence: true

  belongs_to :artist
  has_many :tracks

  has_one_attached :cover_art

  def display_artist_name
    artist&.name || 'Unknown Artist'
  end
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :release
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/e_ps_controller.rb
# app/controllers/eps_controller.rb

class EPsController < ApplicationController
  before_action :set_ep, only: [:show, :edit, :update, :destroy]

  def index
    @eps = EP.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @eps }
    end
  end

  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @ep }
    end
  end

  def new
    @ep = EP.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @ep }
    end
  end

  def create
    @ep = EP.new(ep_params)
    if @ep.save
      respond_to do |format|
        format.html { redirect_to @ep, notice: 'EP creado exitosamente.' }
        format.json { render json: @ep, status: :created, location: @ep }
      end
    else
      respond_to do |format|
        format.html { render 'new' }
        format.json { render json: @ep.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    if @ep.update(ep_params)
      respond_to do |format|
        format.html { redirect_to @ep, notice: 'EP actualizado exitosamente.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { render 'edit' }
        format.json { render json: @ep.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @ep.destroy
    respond_to do |format|
      format.html { redirect_to eps_url, notice: 'EP eliminado exitosamente.' }
      format.json { head :no_content }
    end
  end

  private

  def set_ep
    @ep = EP.find(params[:id])
  end

  def ep_params
    params.require(:ep).permit(:title, :artist_id, :release_date, :other_attributes)
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/discography_helper.rb
module DiscographyHelper
end

app/helpers/e_ps_helper.rb
module EPsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AtklRecords2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "buttons", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="https://kit.fontawesome.com/4fd0c3dd1a.js" crossorigin="anonymous"></script>
    <!-- En el head de tu layout o página -->
    <script src="https://cdn.jsdelivr.net/npm/alpinejs@2.x.x/dist/alpine.min.js" defer></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css" rel="stylesheet" />

  </head>
  <body class="bg-slate-950">
    <%= render 'shared/navbar' %>
    <%= yield %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.turbo.min.js"></script>

  </body>
</html>

app/views/shared/_artist_card.html.erb
<!-- app/views/shared/_artist_card.html.erb -->
<div class="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-black dark:border-gray-700">
  <%= link_to artist_path(artist) do %>
    <% if artist.profile_picture.attached? %>
      <%= image_tag rails_blob_url(artist.profile_picture), class: "rounded-t-lg" %>
    <% else %>
      <!-- Agrega una imagen de respaldo o estilo alternativo si no hay imagen adjunta -->
      <%= image_tag "avatar.jpg", class: "rounded-t-lg" %>
    <% end %>
  <% end %>
  <div class="p-5">
    <%= link_to artist_path(artist) do %>
      <h5 class="mb-2 text-2xl font-bold tracking-tight text-gray-900 text-center dark:text-white">
        <%= artist.name %>
      </h5>
    <% end %>
    <p class="mb-3 font-normal uppercase text-center text-gray-700 dark:text-gray-400">
      <%= artist.profession %>
    </p>
    <!-- Agrega enlaces a las redes sociales del artista aquí -->
    <!-- Por ejemplo: Twitter, Instagram, Facebook -->
    <!-- Puedes personalizar esto según las redes sociales que desees mostrar -->
    <div class="flex space-x-4 text-2xl justify-center">
      <!-- Agrega los iconos de las redes sociales aquí -->
      <!-- Por ejemplo, usa font-awesome o cualquier conjunto de iconos que prefieras -->
      <a href="#" class="text-gray-500 dark:text-gray-400 hover:text-blue-500 dark:hover:text-blue-300">
        <!-- Icono de Twitter -->
        <i class="fab fa-twitter"></i>
      </a>
      <a href="#" class="text-gray-500 dark:text-gray-400 hover:text-red-500 dark:hover:text-red-300">
        <!-- Icono de Instagram -->
        <i class="fab fa-instagram"></i>
      </a>
      <a href="#" class="text-gray-500 dark:text-gray-400 hover:text-blue-800 dark:hover:text-blue-600">
        <!-- Icono de Facebook -->
        <i class="fab fa-facebook"></i>
      </a>
    </div>
  </div>
</div>

app/views/shared/_release_card.html.erb
<!-- app/views/shared/_release_card.html.erb -->
<div class="max-w-sm w-max text-white text-center bg-white border border-gray-200 rounded-lg shadow dark:bg-black dark:border-gray-700">
  <% if release.cover_art.attached? %>
    <%= image_tag rails_blob_url(release.cover_art), class: "rounded-lg max-w-full" %>
  <% end %>
  <h3 class="text-xl font-bold mt-2"><%= release.title %></h3>
  <h3 class="text-lg font-bold mt-2"><%= release.artist.name %></h3>
  <p class="text-sm text-gray-500"><%= release.catalogue %></p>
  <% if release.bandcamp_embed_code.present? %>
    <div >
      <div class="p-4">
        <%= raw release.bandcamp_embed_code %>
      </div>
      <%= render(ButtonComponent.new(type: 'buy', text: 'BUY')) %>
    </div>
  <% end %>
  <!-- Enlace de Edición -->
  <% if current_admin_user %>
    <%= link_to 'Editar', edit_release_path(release), class: 'edit-release-link', remote: true %>
    <%= link_to "Eliminar", release_path(release), method: :delete, data: { confirm: "¿Estás seguro de que quieres eliminar este release?" }, class: "text-red-500 hover:text-red-700 ml-2" %>
  <% end %>
</div>